###  load all movies
GET http://localhost:1234/movies

### load just one movie by id movie
GET http://localhost:1234/movies/008a774e-a84b-11ef-aa11-fc5ceea1e8e5

### load all movies by genre
GET http://localhost:1234/movies?genre=Worship

### Create a movie 
POST http://localhost:1234/movies
Content-Type: application/json

{
  "title": "God's not dead 2",
  "year": 2016,
  "director": "God",
  "duration": 140,
  "poster": "https://i.ebayimg.com/images/g/4goAAOSwMyBe7hnQ/s-l1200.webp",
  "genre": [
    "Worship",
    "Drama"
  ],
  "rate": 9.8
}

### Update a part of movie
PATCH http://localhost:1234/movies/f5c686d5-2613-448f-b314-7aad2532a82f
Content-Type: application/json

{
  "year": 2016
}

### Delete one movie
DELETE http://localhost:1234/movies/e3fb5b0b-b423-42b8-9e6e-8f49f4bf0e19

###
GET https://rest-api-deploy-drab.vercel.app/movies